### ISSUE TITLE
Support for JDK8 rpm install

### ISSUE THREAD

**Issue by samangarg** [agileorbit-cookbooks/java#269]
Do you have any plans to support JDK 8 installation via rpm? As of now, it looks like it supports only tar but no rpm.

recipes/default.rb

if node['java']['install_flavor'] != 'windows'
  if node['java']['jdk_version'].to_i == 8 and node['java']['install_flavor'] != 'oracle'
    Chef::Application.fatal!("JDK 8 is currently only provided with the Oracle JDK")
  end
end

**Comment by MikeTLive** [comment]
since there are 3 different oracle flavors you may try a string comparison which will allow all of oracle, oracle_i386, and oracle_rpm. I'm not so sure about overloading the flavor to also have sub-flavors, but this seems a simple enough possible solution. :

```
if node['java']['jdk_version'].to_i == 8 and !node['java']['install_flavor'].to_s.start_with?("oracle")
  Chef::Application.fatal!("JDK 8 is currently only provided with the Oracle JDK")
end
```

**Comment by erichelgeson** [comment]
Installing via RPM is useful when there is a repo to connect to. Since oracle does not provide one, and if you have one you can just use chefs built in resource to install it, this cookbook wont be supporting downloading and installing the rpm for you.

**Comment by MikeTLive** [comment]
hi eric, thanks for maintaining this cookbook.

the community java cookbook is a direct dependency of many other community cookbooks. having a common cookbook that we can all make use of is a great benefit to the entire community. We have been using this and other community cookbooks with great success.

as a best practice, we maintain a local yum repo for our packages. this includes the oracle jdk8 rpm.
we found some simple enhancements that can be made to this cookbook to enable its continuing support of this local yum repo, and the read me description for the oracle_rpm recipe fits that use perfectly.
oracle, in addition to providing the tgz, has side by side the rpm, which is where we pull it from.

what i don't understand, however, is why you would place a public yum repo hosted by oracle as a requirement for rpm support in this cookbook.

If i am understanding you correctly, your suggested workaround is to not use this cookbook at all and instead use the vanilla package resource if we want to install oracle jdk from rpm.
Is that correct?

Since there are so many cookbooks dependent upon the community java cookbook, this would mean that we, and any others who use oracle jdk8 via rpm, would need to create a fork of this cookbook, or a new one entirely.

i'm not understanding the reason and issues behind discontinuing or leaving broken this basic function.
Can you elaborate? maybe we can come to a more beneficial resolution for the many consumers of this cookbook who also use the oracle rpm from a local yum repo on their systems.
